{
  inputs = {
    #nixpkgs.url = "github:dev-null-undefined/nixpkgs?ref=nixos-unstable";
    nixpkgs.url = "github:NixOs/nixpkgs/nixos-unstable";
    nixpkgs-stable.url = "github:NixOS/nixpkgs/nixos-22.11";
    nixpkgs-master.url = "github:NixOS/nixpkgs/master";

    nixos-hardware.url = "github:NixOS/nixos-hardware/master";

    nixpkgs-dev-null.url = "github:dev-null-undefined/nixpkgs/master";
    nixpkgs-webcord.url = "github:dev-null-undefined/nixpkgs/webcord";
    nixpkgs-testing.url = "github:dev-null-undefined/nixpkgs/master";

    flake-utils.url = "github:numtide/flake-utils";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # https://github.com/thiagokokada/nix-alien
    # Run unpatched binaries on Nix/NixOS
    nix-alien = {
      url = "github:thiagokokada/nix-alien";
      inputs = {
        nixpkgs.follows = "nixpkgs-stable";
        flake-utils.follows = "flake-utils";
      };
    };

    hyprland.url = "github:hyprwm/Hyprland";
    hyprland-contrib.url = "github:hyprwm/contrib";
  };

  outputs = {
    self,
    nixpkgs,
    nixpkgs-stable,
    nixpkgs-master,
    nixos-hardware,
    nixpkgs-dev-null,
    nixpkgs-webcord,
    nixpkgs-testing,
    flake-utils,
    home-manager,
    nix-alien,
    hyprland,
    hyprland-contrib,
  } @ inputs: let
    hostConfigs = [
      {
        hostname = "idk";
        #modules = [./modules/nixos/autogenerated/generator.nix];
      }
      {
        hostname = "oracle-server";
        system = "aarch64-linux";
      }
      {hostname = "homie";}
    ];

    homeConfigs =
      builtins.map (
        config:
          config
          // {
            username = "martin";
          }
      )
      hostConfigs;

    lib = import ./lib {inherit inputs self;};
  in
    {
      inherit lib;
      nixosModules = import ./modules/nixos;
      home-managerModules = import ./modules/home-manager;
      overlays = import ./overlays {inherit inputs self;};

      nixosConfigurations =
        builtins.foldl' (
          acc: config:
            {
              "${config.hostname}" = nixpkgs.lib.nixosSystem (lib.internal.mkHost config);
              "${config.hostname}-vm" = nixpkgs.lib.nixosSystem (lib.internal.mkHost (config
                // {
                  modules =
                    (config.modules or [])
                    ++ [
                      ./modules/isVM/implementation.nix
                    ];
                }));
            }
            // acc
        ) {}
        hostConfigs;
      homeConfigurations =
        builtins.foldl' (
          acc: config:
            {
              "${config.username}@${config.hostname}" =
                home-manager.lib.homeManagerConfiguration
                (lib.internal.mkHome config);
            }
            // acc
        ) {}
        homeConfigs;
    }
    // (flake-utils.lib.eachDefaultSystem (system: {
      packages = lib.internal.mkPkgsWithOverlays system;
      formatter = nixpkgs.legacyPackages.${system}.alejandra;
    }));
}
