# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ 
      (modulesPath + "/installer/scan/not-detected.nix")
      <nixos-hardware/msi/gs60>
    ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Air plane mode fix
  boot.kernelParams = [ "acpi_osi=!" ''acpi_osi="Windows 2006"'' ];

  # C perf debugging variables
  boot.kernel.sysctl = {
    "kernel.perf_event_paranoid" = true;
    "kernel.kptr_restrict" = false;
  };

  # lid close action
  services.logind.lidSwitch = "ignore";
  services.logind.lidSwitchDocked = "ignore";
  services.logind.extraConfig = "HandleLidSwitch=ignore";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/feee7f36-8bcc-4d80-8626-086896503105";
      fsType = "ext4";
    };
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8d7d4e81-0760-4650-b847-5aa472286c09";
      fsType = "ext4";
    };
  
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DA0A-EAB3";
      fsType = "vfat";
    };
  
  fileSystems."/mnt/windows" = 
    {
      device = "/dev/disk/by-uuid/905CDBC35CDBA1F0";
      fsType = "ntfs-3g";
      options = [ "user" "rw" "utf8" "noauto" "umask=000" "uid=1000" ];
    };

  swapDevices = [{
      device = "/dev/nvme1n1p2";
  }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
