{...}: {
  # Lanzaboote replaces systemd-boot with a UEFI stub signed by sbctl-managed
  # keys under our control (PK/KEK/db generated by `sbctl create-keys` and
  # stored in /var/lib/sbctl). Once those keys are enrolled in firmware and
  # Secure Boot is enabled in BIOS, only kernel/initrd images we sign will
  # boot.
  #
  # Check current state with `sbctl status` / `sbctl list-files`.
  boot.lanzaboote = {
    enable = true;
    pkiBundle = "/var/lib/sbctl";
    # ESP is only 1.1G — without a cap, lanzaboote tries to install a UKI per
    # generation and runs out of space immediately. Keep last 10.
    configurationLimit = 10;
  };

  boot.loader = {
    systemd-boot.enable = false;
    efi.canTouchEfiVariables = true;
  };
}
